name: Build & Deploy

on: [push]

env:
  NODE_VERSION: 11.x

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 11.x
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build
