name: Build & Deploy

on: [push]

env:
  NODE_VERSION: 11.x

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 11.x
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: Install SSH key
        env:
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: mkdir ~/.ssh && echo ${SSH_PUBLIC_KEY} >> ~/.ssh/id_rsa.pub && echo ${SSH_PRIVATE_KEY} >> ~/.ssh/id_rsa
      - name: Set SSH Key Permissions
        run: chmod 600 ~/.ssh/id_rsa
      - name: SSH
        run: ls -la ~/.ssh && cat ~/.ssh/id_rsa
      - name: Copy Build to Server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
        run: scp -r -o StrictHostKeyChecking=no ./dist ${SSH_USER}:~/
